read -p "Please enter your Wazuh FQDN: " fqdn

echo "FQDN specified $fqdn"


wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.2-1_amd64.deb && sudo WAZUH_MANAGER="$fqdn" dpkg -i ./wazuh-agent_4.7.2-1_amd64.deb
apt-get install -y auditd && systemctl enable auditd && systemctl kill auditd && apt-get install rsyslog


cp /etc/audit/auditd.conf /etc/audit/auditd.conf_backup

echo local_events = yes > /etc/audit/auditd.conf
echo write_logs = yes >> /etc/audit/auditd.conf
echo log_file = /var/log/audit/audit.log >> /etc/audit/auditd.conf
echo log_group = root >> /etc/audit/auditd.conf
echo log_format = RAW >> /etc/audit/auditd.conf
echo flush = INCREMENTAL_ASYNC >> /etc/audit/auditd.conf
echo freq = 50 >> /etc/audit/auditd.conf
echo max_log_file = 8 >> /etc/audit/auditd.conf
echo num_logs = 5 >> /etc/audit/auditd.conf
echo priority_boost = 4 >> /etc/audit/auditd.conf
echo disp_qos = lossy >> /etc/audit/auditd.conf
echo dispatcher = /sbin/audispd >> /etc/audit/auditd.conf
echo name_format = NONE >> /etc/audit/auditd.conf
echo ##name = mydomain >> /etc/audit/auditd.conf
echo max_log_file_action = ROTATE >> /etc/audit/auditd.conf
echo space_left = 75 >> /etc/audit/auditd.conf
echo space_left_action = SYSLOG >> /etc/audit/auditd.conf
echo verify_email = yes >> /etc/audit/auditd.conf
echo action_mail_acct = root >> /etc/audit/auditd.conf
echo admin_space_left = 50 >> /etc/audit/auditd.conf
echo admin_space_left_action = SUSPEND >> /etc/audit/auditd.conf
echo disk_full_action = SUSPEND >> /etc/audit/auditd.conf
echo disk_error_action = SUSPEND >> /etc/audit/auditd.conf
echo use_libwrap = yes >> /etc/audit/auditd.conf
echo ##tcp_listen_port = 60 >> /etc/audit/auditd.conf
echo tcp_listen_queue = 5 >> /etc/audit/auditd.conf
echo tcp_max_per_addr = 1 >> /etc/audit/auditd.conf
echo ##tcp_client_ports = 1024-65535 >> /etc/audit/auditd.conf
echo tcp_client_max_idle = 0 >> /etc/audit/auditd.conf
echo enable_krb5 = no >> /etc/audit/auditd.conf
echo krb5_principal = auditd >> /etc/audit/auditd.conf
echo ##krb5_key_file = /etc/audit/audit.key >> /etc/audit/auditd.conf
echo distribute_network = no >> /etc/audit/auditd.conf





##Enable Syslog UDP
echo "*.* @$fqdn:514" >> /etc/rsyslog.conf

#Enable Syslog TCP
echo "*.* @@"$fqdn":514" >> /etc/rsyslog.conf


##ENABLE Verbose Logging for SSH##
echo LogLevel VERBOSE >> /etc/ssh/sshd_config


echo # This file is automatically generated from /etc/audit/rules.d > /etc/audit/audit.rules
echo -D >> /etc/audit/audit.rules
echo -b 8192 >> /etc/audit/audit.rules
echo -f 1 >> /etc/audit/audit.rules
echo --backlog_wait_time 60000 >> /etc/audit/audit.rules
echo # Monitor access and modifications to sensitive files >> /etc/audit/audit.rules
echo -w /etc/passwd -p wa -k identity >> /etc/audit/audit.rules
echo -w /etc/shadow -p wa -k identity >> /etc/audit/audit.rules
echo -w /var/log/sudo.log -p wa -k actions >> /etc/audit/audit.rules
echo -w /var/log/wtmp -p wa -k logins >> /etc/audit/audit.rules
echo -w /var/log/btmp -p wa -k logins >> /etc/audit/audit.rules
echo -w /var/run/utmp -p wa -k logins >> /etc/audit/audit.rules
echo -w /etc/cron.allow -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/cron.d/ -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/cron.daily/ -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/cron.hourly/ -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/cron.monthly/ -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/cron.weekly/ -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/crontab -p wa -k cron_jobs >> /etc/audit/audit.rules
echo -w /etc/ -p wa -k cfg_changes >> /etc/audit/audit.rules
echo -w /boot/ -p wa -k boot_changes >> /etc/audit/audit.rules
echo -w /var/log/ -p wa -k log_modification >> /etc/audit/audit.rules
echo -w /home/ -p wa -k home_directory >> /etc/audit/audit.rules
echo -w /etc/ssh/sshd_config -p wa -k ssh_changes >> /etc/audit/audit.rules
echo -w /etc/ssh/ssh_config -p wa -k ssh_changes >> /etc/audit/audit.rules
echo -w /root/.ssh/authorized_keys -p wa -k ssh_keys >> /etc/audit/audit.rules
echo # Monitor kernel module changes >> /etc/audit/audit.rules
echo -w /sbin/insmod -p x -k module_change >> /etc/audit/audit.rules
echo -w /sbin/rmmod -p x -k module_change >> /etc/audit/audit.rules
echo -w /sbin/modprobe -p x -k module_change >> /etc/audit/audit.rules
echo -a always,exit -F arch=b64 -S init_module -S delete_module -k module_change >> /etc/audit/audit.rules
echo # Monitor execution of privileged commands >> /etc/audit/audit.rules
echo -a always,exit -F arch=b64 -S execve -F uid=0 -k privileged_cmds >> /etc/audit/audit.rules
echo -a always,exit -F arch=b64 -S execve -F euid=0 -k privileged >> /etc/audit/audit.rules
echo # Monitor network utilities >> /etc/audit/audit.rules
echo -w /sbin/ifconfig -p x -k network_utilities >> /etc/audit/audit.rules
echo -w /sbin/route -p x -k network_utilities >> /etc/audit/audit.rules
echo -w /usr/bin/netstat -p x -k network_utilities >> /etc/audit/audit.rules
echo -w /usr/bin/nmap -p x -k network_utilities >> /etc/audit/audit.rules
echo -w /usr/bin/wget -p x -k network_utilities >> /etc/audit/audit.rules
echo # Monitor user and group management >> /etc/audit/audit.rules
echo -w /usr/sbin/useradd -p x -k user_mgmt >> /etc/audit/audit.rules
echo -w /usr/sbin/userdel -p x -k user_mgmt >> /etc/audit/audit.rules
echo -w /usr/sbin/usermod -p x -k user_mgmt >> /etc/audit/audit.rules
echo -w /usr/sbin/groupadd -p x -k user_mgmt >> /etc/audit/audit.rules
echo -w /usr/sbin/groupdel -p x -k user_mgmt >> /etc/audit/audit.rules
echo -w /usr/sbin/groupmod -p x -k user_mgmt >> /etc/audit/audit.rules
echo # Monitor file deletion actions >> /etc/audit/audit.rules
echo -a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F uid=0 -k file_deletion >> /etc/audit/audit.rules
echo -a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F uid=0 -k file_deletion >> /etc/audit/audit.rules
echo # Monitor time changes >> /etc/audit/audit.rules
echo -a always,exit -F arch=b64 -S adjtimex -S settimeofday -S clock_settime -k time_change >> /etc/audit/audit.rules
echo -w /etc/localtime -p wa -k time_change >> /etc/audit/audit.rules
echo # Monitor network configuration changes >> /etc/audit/audit.rules
echo -w /etc/network/ -p wa -k network_change >> /etc/audit/audit.rules
echo -w /etc/hosts -p wa -k network_change >> /etc/audit/audit.rules
echo -w /etc/resolv.conf -p wa -k network_change >> /etc/audit/audit.rules
echo # Monitor authentication logs >> /etc/audit/audit.rules
echo -w /var/log/auth.log -p wa -k auth_log >> /etc/audit/audit.rules
echo # Monitor PAM configuration changes >> /etc/audit/audit.rules
echo -w /etc/pam.d/ -p wa -k pam_changes >> /etc/audit/audit.rules
echo # Monitor changes to system binaries >> /etc/audit/audit.rules
echo -w /bin/ -p wa -k system_binaries >> /etc/audit/audit.rules
echo -w /sbin/ -p wa -k system_binaries >> /etc/audit/audit.rules
echo -w /usr/bin/ -p wa -k system_binaries >> /etc/audit/audit.rules
echo -w /usr/sbin/ -p wa -k system_binaries >> /etc/audit/audit.rules
echo -w /lib/ -p wa -k libraries >> /etc/audit/audit.rules
echo -w /usr/lib/ -p wa -k libraries >> /etc/audit/audit.rules
echo # Monitor failed access attempts >> /etc/audit/audit.rules
echo -a always,exit -F arch=b64 -S open -F success=0 -k access_denied >> /etc/audit/audit.rules



##Check Rules Syntax and apply them
augenrules --check

#Check Rules syntax errors
auditctl -R /etc/audit/audit.rules

#Check Applied rules
auditctl -l

systemctl restart ssh
systemctl daemon-reload 
systemctl enable rsyslog
systemctl enable wazuh-agent 
systemctl enable auditd




systemctl stop rsyslog
systemctl stop auditd
systemctl stop wazuh-agent


systemctl start rsyslog
systemctl start auditd
systemctl start wazuh-agent

